---

- name: Create New Folder to Store Data
  ansible.builtin.file:
    path: '{{ mount_point }}'
    state: directory
  become: true
  tags:
  - install 
  - mount
  - folder

  # Partion A Extra Disk 
- name: Create Partition
  community.general.parted:
    #align: '{{ item.align | default(omit) }}'
    #device: '{{ item.device }}'
    device: /dev/sdb
    #flags: '{{ item.flags | default(omit) }}'
    #fs_type: '{{ item.fs_type | default(omit) }}'
    #fs_type: ext4
    #label: '{{ item.label | default("gpt") }}'
    #name: '{{ parted.name | default(omit) }}'
    #name: sdb
    number : 1 
    #number: '{{ item.number | default(omit) }}'
    #part_end: '{{ item.part_end | default(omit) }}'
    #part_start: '{{ item.part_start | default(omit) }}'
    #part_type: '{{ item.part_type | default(omit) }}'
    #resize: '{{ item.resize | default(omit) }}'
    state: present
    #state: '{{ item.state | default(omit) }}'
    #unit: '{{ item.unit | default(omit) }}'
  #with_items: "{{ parted }}"
  become: true
  tags:
  - mount

# Format Parrtion
- name: Format Partition
  community.general.filesystem:
    #dev: '{{ item.dev }}'
    dev: /dev/sdb1
    #force: '{{ item.force | default(omit) }}'
    #fstype: '{{ item.fstype }}'
    fstype: ext4
    #opts: '{{ item.opts | default(omit) }}'
    #resizefs: '{{ item.resizefs | default(omit) }}'
    #state: '{{ item.state | default(omit) }}'
  #with_items: "{{ filesystem }}"
  become: true
  tags:
  - mount
  

# Mount Point
- name: Mount Point
  ansible.posix.mount:
    #backup: '{{ item.backup | default(omit) }}'
    #boot: '{{ item.boot | default(omit) }}'
    #ump: '{{ item.dump | default(omit) }}'
    #fstab: '{{ item.fstab | default(omit) }}'
    fstype: '{{ item.fstype }}'
    fstype: ext4
    #opts: '{{ item.opts | default("defaults") }}'
    #passno: '{{ item.pass | default(omit) }}'
    #path: '{{ item.path }}'
    path: /data/mongodb
    #src: '{{ item.dev }}'
    src: /dev/sdb1
    #state: '{{ item.state | default("mounted") }}'
    state: mounted
  #with_items: "{{ mount }}"
  become: true
  tags:
  - mount