---

- hosts: mongodb
  become: true
  vars:
    repli: true
    partition: true
    mount_point: true
  roles:
    # Mounted disk first
    - mounted_disk
    #  ansible.builtin.inclue_role:
    # - mounted_disk   
    #- name: Install mongodb
    #  absible.builtin.inclue_role:
    - mongodb_install
        