--- 

- name: Enable Replicaset Config File
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_conf_path }}/mongod.conf"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  notify:
    - "restart mongodb"
  when: repli
  tags:
  - replicaset


# Install ansible galaxy first 
# ansible-galaxy collection install community.mongodb
- name: Init Replicaset
  community.mongodb.mongodb_replicaset:
    replica_set: "{{ replicaset_name }}"
    login_port: "{{ mongodb_port }}"
    login_user: " {{ mongodb_user }}"
    login_password: "{{ mongodb_passwd }}"
    validate: true
    members: 
    - worker1:27017
    - worker2:27017
    - worker3:27017 
  when: inventory_hostname in groups['master'] and repli
  become: true
  tags:
  - replicaset
  