--- 

- name: Import list file for Mongodb
  template:
    src: mongodb_repo.list.j2
    dest: "{{ mongodb_key_store }}"
    #owner: "{{ mongodb_user }}"
    #group: "{{ mongodb_group }}"
  tags:
  - install
  - apt

- name: Import Mongodb key
  ansible.builtin.apt_key:
    url: "{{ mongodb_repo }}"
    state: present
    # store keyfile
    #file: "{{ mongodb_key_store }}"
  become: true
  tags:
  - install
  - apt

- name: Update package
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: present
  become: true
  tags:
  - install
  - apt

- name: Install mongodb-org
  apt:
    name: mongodb-org
    state: present
  become: true 
  tags:
  - apt
  - install