---
# tasks file for mongodb_install

- name: Import list file for Mongodb
  template:
    src: mongodb_repo.list.j2
    dest: "{{ mongodb_key_store }}"
    #owner: "{{ mongodb_user }}"
    #group: "{{ mongodb_group }}"
  tags:
  - install
  - apt

- name: Import Mongodb key
  ansible.builtin.apt_key:
    url: "{{ mongodb_repo }}"
    state: present
    # ignore SSL cert for target url
    validate_certs: false
    # store keyfile
    #file: "{{ mongodb_key_store }}"
  become: true
  tags:
  - install
  - apt

- name: Update package
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: present
  become: true
  tags:
  - install
  - apt

- name: Install mongodb-org
  apt:
    name: mongodb-org
    state: present
  become: true 
  tags:
  - apt
  - install


- name: Create New Folder to Store Data
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  tags:
  - install 
  - mount
  - folder

#- name: Restart Mongodb
#  service: 
#    name: mongod
#    state: restarted
#  become: true
#  tags:
#    - mongodb_restart

#- name: Copy Default Folder
#  ansible.builtin.copy:
#    remote_src: true 
#    src: "{{ mongodb_default_folder }}"
#    dest: "{{ mount_point }}"
#    backup: true
#  register: _copy
#  become: true
#  tags:
#  - install
#  - mount
#  - folder

- name: Delete Default Folder
  ansible.builtin.file:
    path: "{{ mongodb_default_folder }}"
    state: absent
  become: true
  tags:
  - install
  - folder

- name: Create Soft Link 
  ansible.builtin.file:
    src: "{{ mount_point }}"
    dest: "{{ mongodb_default_folder }}"
    state: link
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  #notify: 
  #  - Restart Mongodb
  tags:
  - install
  - folder

- name: Restart Mongodb
  service: 
    name: mongod
    state: restarted
  become: true
  tags:
    - mongodb_restart

# If reply Is True
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: install_dependencies.yml
  when: repli
  tags:
  - replicaset

- name: Init Replicaset
  ansible.builtin.include_tasks:
    file: init_replicaset.yml
  when: repli 
  tags: 
  - replicaset






