---
# tasks file for mongodb_install
- name: Update Repo And Install Mongodb
  ansible.builtin.include_tasks:
    file: install_mongodb.yml
  tags:
  - install

- name: Change Mongodb Default Folder
  ansible.builtin.include_tasks:
    file: change_default_folder.yml
  tags:
  - install
  - folder

# If reply Is True
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: install_dependencies.yml
  when: repli #and inventory_hostname in groups['master']
  tags:
  - replicaset

- name: Init Replicaset
  ansible.builtin.include_tasks:
    file: init_replicaset.yml
  when: repli 
  tags: 
  - replicaset






